### ISSUE TITLE
Search should be designated as "Search" rather than "Archive"

### ISSUE THREAD

**Issue by gsf** [wavefarm/site#143]
Request from @galenjosephhunter:
> Would you retitle wavefarm.org/archive SEARCH (instead of ARCHIVE) above the horizontal rule?
> And would you then remove the "Search" header above the search bar?
> I'm/we're fine with the url string remaining .org/archive.. etc.

**Comment by galenjosephhunter** [comment]
I think this is a closed issue now. We have adopted Search rather than archive. "Archive" will be used in the forthcoming "Transmission Arts Archive" subsite.
