### ISSUE TITLE
Footer at https://wavefarm.org/archive is out-dated

### ISSUE THREAD

**Issue by galenjosephhunter** [wavefarm/site#146]
I just noticed that the footer at https://wavefarm.org/archive is out-dated. 

I didn't realize it wasn't pointing to the same footer that the rest of the wavefarm site does...

See https://wavefarm.org/ for what all footers should be displaying.

**Comment by galenjosephhunter** [comment]
I believe this is still open because the archive footer is not being handled by the same template as all the other wavefarm.org pages?

**Comment by gsf** [comment]
Footer is now up to date.
