### ISSUE TITLE
Archive: broadcasts, shows, and wgxc events link to own pages

### ISSUE THREAD

**Issue by gsf** [wavefarm/site#151]
Instead of linking to items at `/archive/<itemId>`, Links in the result list for broadcasts and shows should link to `/wgxc/schedule/<itemId>` while links for WGXC events should link to `/wgxc/calendar/<itemId>`.

**Comment by galenjosephhunter** [comment]
Amazing to have this working Gabe. Thank you!!!

On Thu, May 21, 2015 at 5:23 PM, Gabriel Farrell <notifications@github.com>
wrote:

> Closed #151 <https://github.com/wavefarm/site/issues/151> via c6b0f22
> <https://github.com/wavefarm/site/commit/c6b0f227f92fc950efaf67e8186a2014cf5b753d>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wavefarm/site/issues/151#event-311103326>.
>



-- 


*Galen Joseph-Hunter**Executive Director*
Wave Farm: Transmission Arts, WGXC 90.7-FM, Media Arts Grants
5662 Route 23 Acra, NY 12405
518-622-2598 (o) | 917-297-1537 (c)
https://wavefarm.org/ <http://wavefarm.org/>
Sign-up for Wave Farm emails <http://eepurl.com/yRqVP>

**Comment by galenjosephhunter** [comment]
Looks like the more at wgxc link in this example still needs work?
https://wavefarm.org/archive/2m6p8p

**Comment by galenjosephhunter** [comment]
Maybe that link should just be removed? Or link to wavefarm.org/wgxc since it's possible that archive files can be related to multiple pages?

**Comment by gsf** [comment]
Those links were added because the data was scattered all over. Now that it isn't they should be removed.

**Comment by gsf** [comment]
Without these links there's no mention of WGXC in items with sites:wgxc. We may want to think about including the site icons on these pages as we've done in the search results. Thoughts, @galenjosephhunter?

**Comment by galenjosephhunter** [comment]
I think the links can be removed WHEN we have related info appearing on archive file pages. Archives pages should include "click to expand" for all TUNE IN / TURN OUT / ARTISTS / BROADCASTS / EVENTS / WORKS, etc. where there is content.
