### ISSUE TITLE
Admin Broadcast/Event Duplication (Priority Functionality)

### ISSUE THREAD

**Issue by galenjosephhunter** [wavefarm/site#164]
We would LOVE a Duplicate button at the bottom of broadcast and event pages. The idea is that once clicked, a new record (not yet saved) populated with all the data from the prior appears. We could then update whatever content needs updating and save.

**Comment by gsf** [comment]
Super priority. This will help Galen and Lynn greatly in manually creating broadcasts for the time being.

**Comment by gsf** [comment]
Also move this to admin.

**Comment by galenjosephhunter** [comment]
Any possibility this could be in place by the end of the weekend?

**Comment by gsf** [comment]
Continuing in wavefarm/admin#102.
