### ISSUE TITLE
LISTEN LIVE Bar updates (Priority Functionality)

### ISSUE THREAD

**Issue by galenjosephhunter** [wavefarm/site#166]
Wider Tab
Color 
Animated?
More Prominent Pop-out option
Add feedback/news tip googlevoice numbers.
Add Pond Station, Outposts feeds (can Listen Live be smart enough to only show what is available?)

**Comment by galenjosephhunter** [comment]
make pop-out player a red button

**Comment by galenjosephhunter** [comment]
http://comm.free103point9.org:8000/status.xsl

**Comment by galenjosephhunter** [comment]
http://locus.creacast.com:9001/wave_farm_pond_station_new_york.mp3

**Comment by gsf** [comment]
How about a red border on the tab?

**Comment by ptberry** [comment]
![player_border_closed](https://cloud.githubusercontent.com/assets/1630488/8071374/236db09c-0ebe-11e5-81cd-3ef6e317e382.jpg)
![player_border_open](https://cloud.githubusercontent.com/assets/1630488/8071376/266d24d0-0ebe-11e5-8afa-780d1fb55f7e.jpg)

Here's what a red border and red POP-OUT PLAYER button might look like anyway.

**Comment by galenjosephhunter** [comment]
Looks great. Let's implement.

On Tue, Jun 9, 2015 at 6:43 PM, Peter Berry <notifications@github.com>
wrote:

> [image: player_border_closed]
> <https://cloud.githubusercontent.com/assets/1630488/8071374/236db09c-0ebe-11e5-81cd-3ef6e317e382.jpg>
> [image: player_border_open]
> <https://cloud.githubusercontent.com/assets/1630488/8071376/266d24d0-0ebe-11e5-8afa-780d1fb55f7e.jpg>
>
> Here's what a red border and red POP-OUT PLAYER button might look like
> anyway.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wavefarm/site/issues/166#issuecomment-110525398>.
>



-- 


*Galen Joseph-Hunter**Executive Director*
Wave Farm: Transmission Arts, WGXC 90.7-FM, Media Arts Grants
5662 Route 23 Acra, NY 12405
518-622-2598 (o) | 917-297-1537 (c)
https://wavefarm.org/ <http://wavefarm.org/>
Sign-up for Wave Farm emails <http://eepurl.com/yRqVP>

**Comment by galenjosephhunter** [comment]
One request is to slightly reduce the thickness of the red, though if possible…


Galen Joseph-Hunter
Executive Director
Wave Farm: Transmission Arts, WGXC 90.7-FM, Media Arts Grants
5662 Route 23 Acra, NY 12405 
518-622-2598 (o) | 917-297-1537 (c)
https://wavefarm.org/ <http://wavefarm.org/>
Sign-up for Wave Farm emails <http://eepurl.com/yRqVP>

**Comment by ptberry** [comment]
You can check this out on dev now: https://dev.wavefarm.org/.

The border is a bit more narrow, though adding extra width to the handle was another of the requests.

**Comment by galenjosephhunter** [comment]
I think it looks great on dev. Let's launch it on production whenever you are able.

**Comment by ptberry** [comment]
@galenjosephhunter: Are these two items still relevant:

Add feedback/news tip googlevoice numbers.
Add Pond Station, Outposts feeds (can Listen Live be smart enough to only show what is available?)

?

**Comment by galenjosephhunter** [comment]
@ptberry  
Let’s just add “feedback@wgxc.org <mailto:feedback@wgxc.org>” under info@wgxc.org <mailto:info@wgxc.org>
Re the Pond Station and Outpost feeds I’ll make a not high-priorty issue for that which we can revisit down the line.




Galen Joseph-Hunter
Executive Director
Wave Farm: Transmission Arts, WGXC 90.7-FM, Media Arts Grants
5662 Route 23 Acra, NY 12405 
518-622-2598 (o) | 917-297-1537 (c)
https://wavefarm.org/ <http://wavefarm.org/>
Sign-up for Wave Farm emails <http://eepurl.com/yRqVP>

**Comment by ptberry** [comment]
Closed by 0903e58d96802e11384d8d74c5f113ab0c4cc673, with  Pond Station and Outpost feeds to move to a new issue.

**Comment by galenjosephhunter** [comment]
Peter, can you also add the nice Pop-out Player button for Wave Farm Radio?
