### ISSUE TITLE
Artists: Category=transmission artist 

### ISSUE THREAD

**Issue by galenjosephhunter** [wavefarm/site#169]
only artists who have the category Transmission Artists should have pages displaying on the Transmission Art Archive. Category=Collaborators should display artist page info as Wave Farm archive pages available via the general search. (Note that both WGXC artist categories will be removed.)

Right now though we have a problem with non Transmission Artists linking through to the archive see Artist link from https://wavefarm.org/wgxc/schedule/7hfypf

**Comment by ptberry** [comment]
@galenjosephhunter : there is updated archive code for generating links to within the /ta subsite now on dev for artist as well as events, shows and broadcasts. Does that take care of this issue or is there more?

**Comment by galenjosephhunter** [comment]
Hi Peter,

If the below is confusing, maybe we should Skype about this later? Are you available at all?

I’m looking at
https://dev.wavefarm.org/admin/f59rcz <https://dev.wavefarm.org/admin/f59rcz>
and
https://dev.wavefarm.org/wgxc/schedule/m9ah9n <https://dev.wavefarm.org/wgxc/schedule/m9ah9n>

and not seeing the behavior that I think we should.

If an artist record shows sites:wgxc, and categories:collaborator, then Artists should appear in the related info at wgxc pages
The artist name should link to the artist bio on the archive. In the case above, https://dev.wavefarm.org/archive/f59rcz <https://dev.wavefarm.org/archive/f59rcz>

If an artist record shows sites:wgxc, and categories:transmission artist, then Artists should appear in the related info at wgxc pages
The artist name should link to the artist bio on the Transmission Arts archive. 

Remember that artist categories “WGXC Host” and “WGXC Collaborator” will be suppressed in admin once Gabe gets to that issue.

Does that make sense?

Galen



Galen Joseph-Hunter
Executive Director
Wave Farm: Transmission Arts, WGXC 90.7-FM, Media Arts Grants
5662 Route 23 Acra, NY 12405 
518-622-2598 (o) | 917-297-1537 (c)
https://wavefarm.org/ <http://wavefarm.org/>
Sign-up for Wave Farm emails <http://eepurl.com/yRqVP>

**Comment by ptberry** [comment]
So the problem here is that the flip side of the relation is missing. So 
the broadcast record:

https://dev.wavefarm.org/admin/m9ah9n

does not have that artist (or any artists, thus the missing ARTISTS 
section).

Need to look at it further, but I think this is a separate issue.

**Comment by galenjosephhunter** [comment]
@ptberry  this shouldn't really be possible... for one side to show related content and not the other.

@gsf  definite admin bug here. how should this best be addressed?

**Comment by ptberry** [comment]
Possible admin issue with bi-direction relation moved to https://github.com/wavefarm/admin/issues/109.
