### ISSUE TITLE
Window overlay for special events

### ISSUE THREAD

**Issue by galenjosephhunter** [wavefarm/site#173]
We have a Pledge Drive that starts June 4. Would it be possible to have a window overlay like we were communicating about recently (which disappears once cached)?

**Comment by galenjosephhunter** [comment]
Remove the featured number limit of 10 that is currently in place

**Comment by galenjosephhunter** [comment]
Deciding to just add an image in the header. Likely with transparent background.

**Comment by ptberry** [comment]
This has now morphed into a pull out tab similar to the listen live bar, only on the right. It will likely be open by default on home, and possible /wgxc home, and present but closed on all other pages.

@gsf are you ok with me implementing something similar to what you did for the listen live bar to get this in the archive?

**Comment by galenjosephhunter** [comment]
Actually this should only appear in the WGXC subsite pages, not across all wavefarm.org, and not archive pages.

**Comment by ptberry** [comment]
Ok got it. Never-mind @gsf.
