### ISSUE TITLE
All locations should display on Broadcasts and Events

### ISSUE THREAD

**Issue by galenjosephhunter** [wavefarm/site#179]
Right now it seems that only the first location listed is displaying, but broadcasts will always have more than one as we list FM, as well as the studio of origin etc,..

**Comment by ptberry** [comment]
True. So presumably this needs to change on the individual broadcast and event pages. What about the calendar pages (where would it further increase the API hit count) as the location contact info remains above the click/fold ?

**Comment by gsf** [comment]
I know you've spent some time on this already, but from the data side it's much easier to just show the name of related locations in the list of broadcasts or events. Is it really a requirement to see the entire address for all locations of all items in the list? This really seems to me like data they could click to the full item to see.

**Comment by galenjosephhunter** [comment]
Waiting for Lynn and Tom to discuss this for broadcasts today. I think location name only is likely fine for broadcasts. It’s trickier for the calendar events though as people (we think) opt to read more based on where an event takes place and don’t always know what town locations names are in sole from the “main” field.

**Comment by ptberry** [comment]
To be clear, I think the only issue is the Calendar pages. We don't show location on the schedule page and it's fine to show everything on individual broadcast and event pages where there are only a few locations at most.

**Comment by galenjosephhunter** [comment]
We need to show locations on schedule pages. Here are the instructions I'm providing staff with regarding the locations field on broadcasts in admin:

locations (hint: enter “WGXC 90.7-FM: Hands-on Radio for all 90.7-FM broadcasts; enter “Wave Farm Radio” for all of those broadcasts; ALSO enter WGXC Hudson, Acra, or Satellite Studio to identify studio location, or for remote broadcasts, enter the physical location of origination.)

**Comment by ptberry** [comment]
Attempting to summarize:

1) Add location name only (not contact info), for all locations, to schedule listings below the click (w/ the description).
2) Add all locations, including contact info, above the click to calendar pages
3) Add all locations, not just first, with full info to individual broadcast and event pages.

Correct?

**Comment by galenjosephhunter** [comment]
Note per each of your items:

1) Add location name only (not contact info), for all locations, to schedule listings below the click (w/ the description)


Actually I think this can be just on the individual broadcast and calendar event pages. Right now only the first location is displaying on broadcast pages, which is the problem. We need all locations listed.
2) Add all locations, including contact info, above the click to calendar pages

Calendar locations are displaying fine at present.

3) Add all locations, not just first, with full info to individual broadcast and event pages.

Correct?


Yes. See above note re 1)

**Comment by ptberry** [comment]
@galenjosephhunter : dev has just been updated to address the main issue (need to show all locations for broadcasts), as well as some related inconsistencies but you should review. Current implementation is as follows:

1) All locations, not just first, are now shown on individual broadcast and event pages.
2) Additional contact info (city, state, postal code, phone) shown in addition to address line for all locations on individual broadcast and event pages
3) Adds missing URL field to event page (was on calendar, but not individual pages)
4) Schedule pages unchanged (no locations shown)
5) Calendar pages unchanged (only first location shown, with full contact info, above the click)

**Comment by galenjosephhunter** [comment]
Looks like the second address is pulling from the first? See https://dev.wavefarm.org/wgxc/schedule/ntdjpe <https://dev.wavefarm.org/wgxc/schedule/ntdjpe>

**Comment by ptberry** [comment]
I think this is some kind of deployment problem. Looking into it.
