### ISSUE TITLE
Can't copy/paste from Calendar in "expanded" view

### ISSUE THREAD

**Issue by galenjosephhunter** [wavefarm/site#183]
https://wavefarm.org/wgxc/calendar click on an event title to expand and then try to copy and past text and the expanded section closes. This is odd, since on the schedule page once can successfully copy and past in expanded view.

**Comment by ptberry** [comment]
Closed via [56ee521](https://github.com/wavefarm/site/commit/56ee52144d2b38ca6f2b0d7a99ae87d5e58d2a47)
