### ISSUE TITLE
Empty related items sections should not show up on item/show/broadcast/event/artist/works pages.

### ISSUE THREAD

**Issue by ptberry** [wavefarm/site#185]
The sections are build from the related data passed in the main item query but the actual related item data applies further filters that sometimes leaves the sections empty.

For instance while on /wgxc pages only related items that have sites:wgxc should appear. The actual related items queries filter for this but the original item query does not resulting in an empty section.

Not sure how to fix this while maintaining the lazy loading of the actual related item data.

**Comment by ptberry** [comment]
Going to add some "No Results" text for now so at least it doesn't look like an error.

Another band-aid: suppress the "Artists" section within /wgxc to remove one source of the issue. Current logic says artists will never appear within /wgxc (because no artists should have sites:wgxc).

**Comment by ptberry** [comment]
@galenjosephhunter : I propose we close this ticket. The "No Results" bit is not ideal, but possible solutions are non-trivial so I think we should just live with it for a bit and see what kind of an issue it is in practice, creating new tickets as necessary. Go ahead and close this if you agree.

**Comment by galenjosephhunter** [comment]
Okay
