### ISSUE TITLE
TA add an event to notify info@wavefarm.org

### ISSUE THREAD

**Issue by galenjosephhunter** [wavefarm/site#187]
Add an event at wavefarm.org/ta/calendar should automatically assign the event category of international transmission arts event, and alert info@wavefarm.org.

Add an event at wavefarm.org/wgxc/calendar should not be affected as a result.

**Comment by ptberry** [comment]
@galenjosephhunter : The API endpoint should already be setting the category for these to "TA International Calendar" - is that no longer exactly correct? That category name is also currently driving functionality on the TA front end calendars. Let me know if it has changed and I'll update. 

I'll make an API issue for the email part of this as well.

**Comment by galenjosephhunter** [comment]
@peterberry : the category functionality looks perfect. I guess it is just the email notification that needs to be addressed.
