### ISSUE TITLE
Archive page change requests..

### ISSUE THREAD

**Issue by galenjosephhunter** [wavefarm/site#201]
Please see attachment for what the Archive main page should look like.

Also, in the archive footer, please update the ARCHIVE link to: https://wavefarm.org/archive?q=type%3Aaudio%20OR%20type%3Avideo%20OR%20type%3Aimage%20OR%20type%3Atext&date=&date2=&sort=-timestamp 

NOTE: that I've done this on the main site footer, and it wasn't working until I added target="", which is very strange but appears to have tricked things into working...

![screen shot 2015-10-07 at 6 04 05 am](https://cloud.githubusercontent.com/assets/1069607/10334654/9af624ce-6cb9-11e5-9903-4768336496f2.png)

**Comment by gsf** [comment]
The `target=""` was needed because the link was the entire URL, including `https://wavefarm.org`. I've removed it.
