### ISSUE TITLE
Images: Can we prioritize what the representative image is for an Artist, Work, Event?

### ISSUE THREAD

**Issue by galenjosephhunter** [wavefarm/site#7]
Then could there be a photo “gallery” function we can include for additional image? Right now the single image archive functionality is clumsy see: http://transmissionarts.org/work/5w8epk/image and another example is images from the WGXC Gala last weekend. See: https://www.facebook.com/media/set/?set=a.10151420797426652.1073741827.58995676651&type=1

**Comment by galenjosephhunter** [comment]
This is related to the current question/desire to set which image is the representative image for WGXC Shows. We basically need a way to identify which image is the rep image to display. Right now Peter is displaying the first image, but since I can't control the order of the files listed that is not a good solution... (If we can control the order in the new admin, then great. that works for the time being.)

**Comment by gsf** [comment]
In the new admin I believe it will maintain the order in which the images are added. This wouldn't be a permanent solution but could serve us temporarily. Can you test?

**Comment by galenjosephhunter** [comment]
Will happily test, as soon as I can get back into admin. I don’t have access at present (I just sent an email on this.) Thanks!

**Comment by galenjosephhunter** [comment]
Seems to work in the way you describe. This is fine as a temporary solution.
https://dev.wavefarm.org/admin/8vr8cj <https://dev.wavefarm.org/admin/8vr8cj>
https://dev.wavefarm.org/wgxc/schedule/8vr8cj <https://dev.wavefarm.org/wgxc/schedule/8vr8cj>


Galen Joseph-Hunter
Executive Director
Wave Farm: Transmission Arts, WGXC 90.7-FM, Media Arts Grants
5662 Route 23 Acra, NY 12405 
518-622-2598 (o) | 917-297-1537 (c)
https://wavefarm.org/ <http://wavefarm.org/>
Sign-up for Wave Farm emails <http://eepurl.com/yRqVP>

**Comment by gsf** [comment]
Great. I'll still leave this open until we come up with that permanent fix.

**Comment by gsf** [comment]
Closing in favor of #162.
