### ISSUE TITLE
Event pages

### ISSUE THREAD

**Issue by gsf** [wavefarm/site#75]
For the WGXC calendar we need event pages in the archive.

**Comment by galenjosephhunter** [comment]
Is this still open? I thought we were linking WGXC Calendar related search results in the archive directly to their https://wavefarm.org/wgxc/calendar/###### pages.

**Comment by gsf** [comment]
Correct. This can be closed.

**Comment by ptberry** [comment]
This functionality is present but disabled because the production 
archive should not send people into the /wgxc subsite prior to a WGXC 
launch.
